# Site settings
title: Give Joseph Smith a Break!
email: givejosephsmithabreak@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  In the October 2015 General Conference, Elder Neil L. Andersen asked listeners to "give brother Joseph a break".
  Carefully read and ponder the facts found here and consider whether or not Joseph deserves a break.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://givejosephabreak.org" # the base hostname & protocol for your site
twitter_username: givejoeabreak
github_username:  mormonessays

# Build settings
markdown: kramdown
